name: .venv
channels:
  - conda-forge
  - defaults
  - pip
dependencies:
  - python=3.9.16
  - ipykernel=6.28.0
  - featuretools>=1.5.0
  - matplotlib>=3.4.2
  - matplotlib-inline>=0.1.2
  - numpy==1.26.4
  - pandas==2.2.1
  - scikit_learn==1.4.1.post1
  - scipy==1.12.0
  - seaborn>=0.11.1
  - omegaconf==2.3.0
  - loguru==0.7.2
  - streamlit==1.28.1
  - streamlit_lottie==0.0.5